# Generated by Django 4.2.1 on 2023-05-07 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_scraper', '0002_alter_channel_keyword_delete_keyword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='name',
            new_name='link',
        ),
    ]
