# Generated by Django 4.2.1 on 2023-05-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_scraper', '0004_rename_keyword_channel_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='subscriber',
            field=models.TextField(max_length=10),
        ),
    ]
